project:
  type: website
  output-dir: docs
  #pre-render: R/setup.R

website:
  title: "CI12"
  navbar:
    left:
      - href: index.qmd
        text: Home
  sidebar:
    contents:
      - section: "Scientific Research in Innovation Management"
      - text: "Material course for IDEAS and IUVTT students"
        contents:
          - href: 01-introduction/tp1.qmd
  

format:
  html:
    theme:
      - cosmo
#      - assets/custom.scss
    toc: true
    number-sections: false
    html-math-method: mathjax
    freeze: true

execute:
  freeze: auto  # re-render only when source changes
  cache: false