project:
  type: website
  output-dir: docs
  preview:
    port: 4200
    browser: true
  #pre-render: R/setup.R

website:
  title: "CI12"
  navbar:
    left:
      - href: index.qmd
        text: Home
  sidebar:
    contents:
      - section: "Scientific Research in Innovation Management"
      - text: "---"
      - section: "Act I: Bibliometric Analysis"
        contents:
          - text: "CM1: Introduction to Scientific Research"
            href: 01-introduction/index.qmd
          - text: "TD1: VOSviewer -- Visualization of Research Landscape"
            href: 01-introduction/td1.qmd
      - text: "---" 
      - section: "Act II: Literature review"
        contents:
          - text: "On the shoulders of giants"
            href: 02-literature/index.qmd
          - text: "TD2: Bibliometrix -- Networks of Research Landscape"
            href: 02-literature/td2.qmd
  

format:
  html:
    theme:
      - cosmo
#      - assets/custom.scss
    toc: true
    number-sections: false
    html-math-method: mathjax
#    freeze: true

#execute:
#  freeze: auto  # re-render only when source changes
#  cache: false