project:
  type: website
  output-dir: docs
  pre-render: R/setup.R

website:
  title: "CI12"
  navbar:
    left:
      - href: index.qmd
        text: Home


format:
  html:
    theme:
      - litera
      - assets/custom.scss
    toc: true
    number-sections: false
    html-math-method: mathjax
    freeze: true

execute:
  freeze: auto  # re-render only when source changes
  cache: false