---
title: "Research, Innovation & Development"
subtitle: "ENSGSI"
---

# Syllabus


## Instructors

- Fabio A. Cruz Sanchez 
- Mauricio Camargo
- Ferney Osorio
- Alex Gabriel


## Goal of the module:

This introduction course seeks to to Master and Engineering students to the basis of the scientific research in Innovation Management field. 
The main purpose is to understand the process of establishing a research process pipeline, including the literature review, structuration of the research problematic, definition of experimental protocol and hypothesis and presentation of the results in from of a scientific paper. 
Moreover, an overview of the 

This course includes a course in presences and a writing workshop of a first scientific paper. 


# Act I: Bibliometric Analysis

## Presentation of the day

```{=html}
<iframe class="slide-deck" src="01-introduction/index.html" width="100%"
    height="500"></iframe>
```


## TD1: Visualization of Scientific Landscapes 

### TD1 Presentation

```{=html}
<iframe class="slide-deck" src="01-introduction/td1.html" width="100%"
    height="500"></iframe>
```

### Step 1: Web Of Science

```{=html}
<iframe class="slide-deck" src="01-introduction/00-wos.html" width="100%"
    height="500"></iframe>
```


### Step 2: VosViewer

```{=html}
<iframe class="slide-deck" src="01-introduction/01-vosviewer.html" width="100%"
    height="500"></iframe>

```


### Step 3: VosViewer for Patents

```{=html}
<iframe class="slide-deck" src="01-introduction/03-patents.html" width="100%"
    height="500"></iframe>

```


# Act II: Literature review


## What is a Literature Review 

```{=html}
<iframe class="slide-deck" src="02-literature/index.html" width="100%"
    height="500"></iframe>
```

## TD2: Bibliometrix & Reading Scientific literature

```{=html}
<iframe class="slide-deck" src="02-literature/td2.html" width="100%"
    height="500"></iframe>
```

### Step 1: Web Of Science

```{=html}
<iframe class="slide-deck" src="02-literature/00-wos.html" width="100%"
    height="500"></iframe>
```


### Step 2: Bibliometrix

```{=html}
<iframe class="slide-deck" src="02-literature/01-bibliometrix.html" width="100%"
    height="500"></iframe>

```
