---
title: 'TD1 : Landscape of research via Vosviewer'
format:
  # html:
  #   toc: false
  docx:
    toc: false
    number-sections: false
    highlight-style: github
    linkcolor: blue
    urlcolor: blue
    link-citations: yes
    #reference-doc: ../Template.docx
  # pdf:
  #   documentclass: article
  #   classoption: [onecolumn]
  #   geometry: [left=2cm,top=1.5cm,right=2cm,bottom=1.5cm]
  #   papersize: a4paper
  #   toc: false
  #   number-sections: false
  #   colorlinks: true
  #   fontsize: 11pt
  #   linkcolor: blue
  #   urlcolor: blue
  #   link-citations: yes
  #   include-in-header: [assets/preamble.tex]
  #   include-before-body: [assets/titlepage.tex]
  #   keep-tex: true

    #fontfamily: arial 
execute:
  echo: false
  warning: false    
#bibliography: [assets/library.bib, assets/OSTRL.bib]
#csl: assets/sage-vancouver.csl
subparagraph: yes
---



## Goal of the Exercise: 

- Identify the scientific databases to collect data.
- Practical  the software for lanscape research such as VosVierwer


## Exercise 1: Identification of the research question

1.	Work in a group of 2 or 3 max persons.
1. Define a **topic subject of interest** that you will work together. (Use the help document)[]
1. Identify the main keywords to use in the searching process. 
1. Define a research question with the purpose to explore the 
1. Go to Web of Science page and download the documents regarding the subject. 
1. Use and analize the different data visualization proposed by WbS interface.

1. Answer the following questions:

  1. Identify the countries or geographical regions where the subject has been studied, generating the most important number of research outputs?. 

  1. What are the main **funding agencies** of those research outputs? Are there relationship of the funding researches and the countries with hte most research outputs?. what could be the links or dynamics that you can infer? 
  
  1. Identify the **research areas** that link the subject of study. Analyze if there is a link between these areas.  Make an argumentation ana analaysis.


1. Finally, download the data associated to this topic in a `.csv` file.  (*You have to download the results in batches of 1000 (max) (e.g. for 1900 results, you need two files 1-1000, and 1001-1900))
<br>


::: callout-note
## Example  


- **Research question Q1:** What is the advancements of the research in the management field on the Covid-19 in the perior 2020-2021?

- **Keywords:** « SARS COV », « COVID 19 », « corona virus » ; Domaine : management ; Période : 2020-2021 
:::

 
## Exercise 2: Landscape review of the the research question

1. Download and install the VosViewer Software.
2. Load the data downloaded and create an Map based on bibliographic data
3. Use the data that you download
4. Make a description and analysis of the clusters identified in the `"Network Visualization"` (take a screenshot of the network visualization obtained with the VOSviewer software).

5. Complete the table : 

| Cluster (# and color) | Main keywod | Associated Keywords |
|------|------|------|
| A    | B    | C    |
| E    | F    | G    |
| A    | G    | G    |

   1. Taking into account the keywords you initially selected, reflect on the identified clusters, and on the relationships between clusters and their keywords.

6. Based on the results of "OVERLAY VISUALIZATION" identify :
   - The keywords that were most considered in the scientific literature during the period, list them taking into account their importance due to their occurrence. What are the relationships between these keywords?
   
   - Identify key issues anticipated in future research and justify why they are relevant for further study. (Note that question 5 can only be done if you have conducted research over a period of more than 1 year)

6. Repeat the VosViewer map creation procedure but this time create a new visualization with the relationships between countries with VosViewer
   - Which countries collaborate the most ?
   - Do these relationships correspond with the countries that publish the most and the results you found with the Web Of Science tools ?

::: callout-warning
## For Arche

For each group, file your report on Moodle presenting the results obtained: Excel and/or Word file

- Filename of the Report on Arche: `[TD1]-[Lastname]-[].pdf` 
:::
